pub mod analyzer_report;
pub mod analyzer_trait;
pub mod elf_analyzer;
pub mod mach_analyzer;
pub mod ole_analyzer;
pub mod openxml_analyzer;
pub mod pdf_analyzer;
pub mod pe_analyzer;
pub mod zip_analyzer;
